<footer>
    <!-- Project links section -->
    <section class="footer-section"  aria-labelledby="project-links-title">
        <h3 id="project-links-title">Project Links</h3>
        <ul>
            <li>
                <a href="https://github.com/106225401/applied-web-project-part-1" target="_blank" rel="noopener">
                    GitHub Repository (Source Code)
                    <span class="sr-only">(opens in new window)</span>
                </a>
            </li>
            <li>
                <a href="https://student-team-cos10026.atlassian.net/jira/software/projects/AWPP1/boards/4" target="_blank" rel="noopener">
                    Jira (Project Management)
                    <span class="sr-only">(opens in new window)</span>
                </a>
            </li>
        </ul>
    </section>

    <!-- Navigation menu section -->
    <section class="footer-section" aria-labelledby="quick-links-title">
        <h3 id="quick-links-title">Quick Links</h3>
        <nav aria-label="Footer navigation">
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Jobs</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About Us</a></li>
            </ul>
        </nav>
    </section>

    <!-- Email contact section -->
    <section class="footer-section" aria-labelledby="contact-us-title">
        <h3 id="contact-us-title">Contact Us</h3>
        <p>Email: <a href="mailto:info@nextgen.com" >info@nextgen.com</a></p>
        <p>Follow Us!</p>
        <span>
            <a href="https://wa.me/60142597095" target="_blank"><img src="images/whatsapp.png" alt="WhatsApp Icon"></a> 
            <a href="https://www.facebook.com/people/Next-Generation-Developers/61590674170023/" target="_blank"><img src="images/facebook.png" alt="Facebook Icon"></a> 
            <a href="https://www.instagram.com/next.gendevs/" target="_blank"><img src="images/instagram.png" alt="Instagram Icon"></a> 
            <a href="https://www.youtube.com/@NextGenDevs-r4o" target="_blank"><img src="images/youtube.png" alt="YouTube Icon"></a>
        </span>
    </section>

    <!-- Copyright-->
    <small class="copyright">Copyright &copy; 2026 NextGen Devs. All rights reserved.</small>
</footer>